language: ruby
sudo: false
rvm:
  - 2.2.1
  - 2.2
  - 2.3.0
bundler_args: --without production
addons:
  postgresql: '9.4'
before_install:
  - gem update bundler
before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
notifications:
  email: false